### ISSUE TITLE
Support for PIRATE (ARRR)

### ISSUE THREAD

**Issue by himu007** [Zondax/ledger-zcash#12] opened 2021-05-08 08:36 UTC
Hello @jleni 

This is a great work you done supporting shielded address of Zcash. I was wondering how much additional work it would be to support PIRATE (ARRR) in Ledger devices?

PirateChain is a Komodo fork which is a ZCash fork and has sapling activated. Repo: https://github.com/PirateNetwork/pirate

Please feel free to ask any questions if you have about the PirateChain (ARRR).

Best regards,

SHossain

**Comment by jleni** [comment] 2022-03-07 10:13
Closed as duplicate of #26

**Closed by jleni** 2022-03-07 10:13 UTC
Labels: P3-Low
